job.type: train
dataset.name: kinship

reciprocal_relations_model:
  class_name: ReciprocalRelationsModel
  base_model:
    type: semigroupe
    +++: +++

model: reciprocal_relations_model

train:
  optimizer.default:
    type: Adam
    args:
      lr: 0.2
      weight_decay: 0.4e-7
  batch_size: 256
  max_epochs: 500

valid:
  early_stopping:
    patience: 10
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test

lookup_embedder:
  initialize: xavier_normal_

semigroupe:
  sub_dim: 5
  number_of_copies: 30

